import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

import { getBlocksToJsonMigrator } from '@payloadcms/db-postgres/migration-utils'
import { fileURLToPath } from 'url'
import path from 'path'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

// Configure migration options (optional)
const BATCH_SIZE = 100 // Number of entities to process per batch
const TEMP_FOLDER = path.resolve(dirname, '.payload-blocks-migration') // Folder path to store migration batch


export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  
  const migrator = getBlocksToJsonMigrator(payload)
  migrator.setTempFolder(TEMP_FOLDER)
  await migrator.collectAndSaveEntitiesToBatches(req, { batchSize: BATCH_SIZE })
  
  await db.execute(sql`
   ALTER TABLE "pages_blocks_home_hero_highlights" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_home_hero_client_logos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_home_hero" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "projAcc" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_why_notionhive_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_why_notionhive" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_service_grid_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_service_grid" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_our_process_block_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_our_process_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_usp_table_columns" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_usp_table_rows" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_usp_table" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_numbers_section_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_numbers_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_testimonials_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_testimonials_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_contact_us_section_list_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_contact_us_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_level_up_c_t_a" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_case_studies_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_case_studies_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_our_approach_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_our_approach" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_brands_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_brands_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_service_details_banner_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_service_details_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_business_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_page_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_title_with_tabs_tabs" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_title_with_tabs" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_book_consultation" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_about_us_strategy_numbers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_about_us_strategy" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_our_story_year_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_our_story" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_awards_recognition_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_awards_recognition" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_our_clients_clients" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_our_clients" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_join_our_team" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_case_studies_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_all_case_studies" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_work_together" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_case_summary" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_case_details_gallery" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_case_details_project" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_case_details_gallery_two" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_case_details" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_included_services_services" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_included_services" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_industry_experience_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_industry_experience" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_our_process_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_our_process" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_life_at_n_h_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_life_at_n_h" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_featured_blog_post" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_blog_posts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_project_discussion" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_office_address_addresses" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_office_address" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_awards_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_awards_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_video_testimonial_videos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_video_testimonial" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_rich_content" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_home_hero_highlights" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_home_hero_client_logos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_home_hero" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_items_v" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_projAcc_v" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_why_notionhive_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_why_notionhive" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_service_grid_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_service_grid" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_our_process_block_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_our_process_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_usp_table_columns" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_usp_table_rows" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_usp_table" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_numbers_section_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_numbers_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_testimonials_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_testimonials_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_contact_us_section_list_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_contact_us_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_level_up_c_t_a" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_case_studies_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_case_studies_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_our_approach_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_our_approach" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_brands_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_brands_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_service_details_banner_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_service_details_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_business_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_page_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_title_with_tabs_tabs" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_title_with_tabs" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_book_consultation" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_about_us_strategy_numbers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_about_us_strategy" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_our_story_year_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_our_story" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_awards_recognition_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_awards_recognition" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_our_clients_clients" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_our_clients" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_join_our_team" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_case_studies_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_all_case_studies" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_work_together" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_case_summary" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_case_details_gallery" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_case_details_project" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_case_details_gallery_two" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_case_details" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_included_services_services" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_included_services" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_industry_experience_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_industry_experience" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_our_process_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_our_process" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_life_at_n_h_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_life_at_n_h" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_featured_blog_post" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_blog_posts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_project_discussion" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_office_address_addresses" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_office_address" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_awards_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_awards_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_video_testimonial_videos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_video_testimonial" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_rich_content" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_home_hero_highlights" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_home_hero_client_logos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_home_hero" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_why_notionhive_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_why_notionhive" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_service_grid_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_service_grid" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_our_process_block_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_our_process_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_usp_table_columns" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_usp_table_rows" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_usp_table" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_numbers_section_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_numbers_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_testimonials_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_testimonials_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_contact_us_section_list_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_contact_us_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_level_up_c_t_a" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_case_studies_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_case_studies_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_our_approach_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_our_approach" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_brands_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_brands_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_service_details_banner_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_service_details_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_business_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_page_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_title_with_tabs_tabs" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_title_with_tabs" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_book_consultation" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_about_us_strategy_numbers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_about_us_strategy" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_our_story_year_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_our_story" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_awards_recognition_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_awards_recognition" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_our_clients_clients" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_our_clients" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_join_our_team" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_case_studies_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_all_case_studies" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_work_together" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_case_summary" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_case_details_gallery" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_case_details_project" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_case_details_gallery_two" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_case_details" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_included_services_services" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_included_services" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_industry_experience_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_industry_experience" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_our_process_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_our_process" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_life_at_n_h_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_life_at_n_h" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_featured_blog_post" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_blog_posts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_project_discussion" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_office_address_addresses" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_office_address" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_awards_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_awards_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_video_testimonial_videos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_video_testimonial" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "services_blocks_rich_content" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_home_hero_highlights" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_home_hero_client_logos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_home_hero" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_why_notionhive_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_why_notionhive" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_service_grid_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_service_grid" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_our_process_block_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_our_process_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_usp_table_columns" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_usp_table_rows" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_usp_table" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_numbers_section_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_numbers_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_testimonials_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_testimonials_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_contact_us_section_list_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_contact_us_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_level_up_c_t_a" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_case_studies_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_case_studies_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_our_approach_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_our_approach" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_brands_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_brands_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_service_details_banner_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_service_details_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_business_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_page_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_title_with_tabs_tabs" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_title_with_tabs" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_book_consultation" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_about_us_strategy_numbers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_about_us_strategy" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_our_story_year_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_our_story" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_awards_recognition_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_awards_recognition" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_our_clients_clients" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_our_clients" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_join_our_team" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_case_studies_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_all_case_studies" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_work_together" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_case_summary" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_case_details_gallery" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_case_details_project" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_case_details_gallery_two" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_case_details" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_included_services_services" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_included_services" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_industry_experience_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_industry_experience" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_our_process_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_our_process" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_life_at_n_h_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_life_at_n_h" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_featured_blog_post" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_blog_posts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_project_discussion" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_office_address_addresses" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_office_address" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_awards_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_awards_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_video_testimonial_videos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_video_testimonial" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_services_v_blocks_rich_content" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_home_hero_highlights" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_home_hero_client_logos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_home_hero" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_why_notionhive_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_why_notionhive" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_service_grid_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_service_grid" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_our_process_block_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_our_process_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_usp_table_columns" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_usp_table_rows" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_usp_table" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_numbers_section_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_numbers_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_testimonials_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_testimonials_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_contact_us_section_list_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_contact_us_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_level_up_c_t_a" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_case_studies_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_case_studies_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_our_approach_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_our_approach" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_brands_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_brands_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_service_details_banner_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_service_details_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_business_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_page_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_title_with_tabs_tabs" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_title_with_tabs" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_book_consultation" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_about_us_strategy_numbers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_about_us_strategy" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_our_story_year_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_our_story" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_awards_recognition_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_awards_recognition" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_our_clients_clients" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_our_clients" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_join_our_team" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_case_studies_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_all_case_studies" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_work_together" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_case_summary" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_case_details_gallery" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_case_details_project" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_case_details_gallery_two" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_case_details" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_included_services_services" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_included_services" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_industry_experience_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_industry_experience" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_our_process_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_our_process" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_life_at_n_h_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_life_at_n_h" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_featured_blog_post" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_blog_posts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_project_discussion" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_office_address_addresses" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_office_address" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_awards_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_awards_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_video_testimonial_videos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_video_testimonial" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "our_work_blocks_rich_content" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_home_hero_highlights" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_home_hero_client_logos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_home_hero" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_why_notionhive_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_why_notionhive" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_service_grid_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_service_grid" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_our_process_block_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_our_process_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_usp_table_columns" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_usp_table_rows" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_usp_table" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_numbers_section_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_numbers_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_testimonials_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_testimonials_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_contact_us_section_list_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_contact_us_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_level_up_c_t_a" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_case_studies_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_case_studies_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_our_approach_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_our_approach" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_brands_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_brands_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_service_details_banner_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_service_details_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_business_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_page_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_title_with_tabs_tabs" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_title_with_tabs" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_book_consultation" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_about_us_strategy_numbers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_about_us_strategy" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_our_story_year_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_our_story" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_awards_recognition_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_awards_recognition" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_our_clients_clients" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_our_clients" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_join_our_team" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_case_studies_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_all_case_studies" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_work_together" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_case_summary" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_case_details_gallery" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_case_details_project" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_case_details_gallery_two" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_case_details" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_included_services_services" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_included_services" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_industry_experience_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_industry_experience" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_our_process_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_our_process" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_life_at_n_h_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_life_at_n_h" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_featured_blog_post" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_blog_posts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_project_discussion" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_office_address_addresses" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_office_address" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_awards_block_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_awards_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_video_testimonial_videos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_video_testimonial" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_our_work_v_blocks_rich_content" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "forms_blocks_checkbox" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "forms_blocks_country" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "forms_blocks_email" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "forms_blocks_message" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "forms_blocks_number" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "forms_blocks_select_options" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "forms_blocks_select" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "forms_blocks_state" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "forms_blocks_text" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "forms_blocks_textarea" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "pages_blocks_home_hero_highlights" CASCADE;
  DROP TABLE "pages_blocks_home_hero_client_logos" CASCADE;
  DROP TABLE "pages_blocks_home_hero" CASCADE;
  DROP TABLE "items" CASCADE;
  DROP TABLE "projAcc" CASCADE;
  DROP TABLE "pages_blocks_why_notionhive_cards" CASCADE;
  DROP TABLE "pages_blocks_why_notionhive" CASCADE;
  DROP TABLE "pages_blocks_service_grid_items" CASCADE;
  DROP TABLE "pages_blocks_service_grid" CASCADE;
  DROP TABLE "pages_blocks_our_process_block_cards" CASCADE;
  DROP TABLE "pages_blocks_our_process_block" CASCADE;
  DROP TABLE "pages_blocks_usp_table_columns" CASCADE;
  DROP TABLE "pages_blocks_usp_table_rows" CASCADE;
  DROP TABLE "pages_blocks_usp_table" CASCADE;
  DROP TABLE "pages_blocks_numbers_section_cards" CASCADE;
  DROP TABLE "pages_blocks_numbers_section" CASCADE;
  DROP TABLE "pages_blocks_testimonials_block_items" CASCADE;
  DROP TABLE "pages_blocks_testimonials_block" CASCADE;
  DROP TABLE "pages_blocks_contact_us_section_list_items" CASCADE;
  DROP TABLE "pages_blocks_contact_us_section" CASCADE;
  DROP TABLE "pages_blocks_level_up_c_t_a" CASCADE;
  DROP TABLE "pages_blocks_case_studies_block_items" CASCADE;
  DROP TABLE "pages_blocks_case_studies_block" CASCADE;
  DROP TABLE "pages_blocks_our_approach_items" CASCADE;
  DROP TABLE "pages_blocks_our_approach" CASCADE;
  DROP TABLE "pages_blocks_brands_block_items" CASCADE;
  DROP TABLE "pages_blocks_brands_block" CASCADE;
  DROP TABLE "pages_blocks_service_details_banner_items" CASCADE;
  DROP TABLE "pages_blocks_service_details_banner" CASCADE;
  DROP TABLE "pages_blocks_business_block" CASCADE;
  DROP TABLE "pages_blocks_page_banner" CASCADE;
  DROP TABLE "pages_blocks_title_with_tabs_tabs" CASCADE;
  DROP TABLE "pages_blocks_title_with_tabs" CASCADE;
  DROP TABLE "pages_blocks_book_consultation" CASCADE;
  DROP TABLE "pages_blocks_about_us_strategy_numbers" CASCADE;
  DROP TABLE "pages_blocks_about_us_strategy" CASCADE;
  DROP TABLE "pages_blocks_our_story_year_items" CASCADE;
  DROP TABLE "pages_blocks_our_story" CASCADE;
  DROP TABLE "pages_blocks_awards_recognition_items" CASCADE;
  DROP TABLE "pages_blocks_awards_recognition" CASCADE;
  DROP TABLE "pages_blocks_our_clients_clients" CASCADE;
  DROP TABLE "pages_blocks_our_clients" CASCADE;
  DROP TABLE "pages_blocks_join_our_team" CASCADE;
  DROP TABLE "pages_blocks_case_studies_banner" CASCADE;
  DROP TABLE "pages_blocks_all_case_studies" CASCADE;
  DROP TABLE "pages_blocks_work_together" CASCADE;
  DROP TABLE "pages_blocks_case_summary" CASCADE;
  DROP TABLE "pages_blocks_case_details_gallery" CASCADE;
  DROP TABLE "pages_blocks_case_details_project" CASCADE;
  DROP TABLE "pages_blocks_case_details_gallery_two" CASCADE;
  DROP TABLE "pages_blocks_case_details" CASCADE;
  DROP TABLE "pages_blocks_included_services_services" CASCADE;
  DROP TABLE "pages_blocks_included_services" CASCADE;
  DROP TABLE "pages_blocks_industry_experience_items" CASCADE;
  DROP TABLE "pages_blocks_industry_experience" CASCADE;
  DROP TABLE "pages_blocks_our_process_items" CASCADE;
  DROP TABLE "pages_blocks_our_process" CASCADE;
  DROP TABLE "pages_blocks_life_at_n_h_items" CASCADE;
  DROP TABLE "pages_blocks_life_at_n_h" CASCADE;
  DROP TABLE "pages_blocks_featured_blog_post" CASCADE;
  DROP TABLE "pages_blocks_blog_posts" CASCADE;
  DROP TABLE "pages_blocks_project_discussion" CASCADE;
  DROP TABLE "pages_blocks_office_address_addresses" CASCADE;
  DROP TABLE "pages_blocks_office_address" CASCADE;
  DROP TABLE "pages_blocks_awards_block_items" CASCADE;
  DROP TABLE "pages_blocks_awards_block" CASCADE;
  DROP TABLE "pages_blocks_video_testimonial_videos" CASCADE;
  DROP TABLE "pages_blocks_video_testimonial" CASCADE;
  DROP TABLE "pages_blocks_rich_content" CASCADE;
  DROP TABLE "pages_rels" CASCADE;
  DROP TABLE "_pages_v_blocks_home_hero_highlights" CASCADE;
  DROP TABLE "_pages_v_blocks_home_hero_client_logos" CASCADE;
  DROP TABLE "_pages_v_blocks_home_hero" CASCADE;
  DROP TABLE "_items_v" CASCADE;
  DROP TABLE "_projAcc_v" CASCADE;
  DROP TABLE "_pages_v_blocks_why_notionhive_cards" CASCADE;
  DROP TABLE "_pages_v_blocks_why_notionhive" CASCADE;
  DROP TABLE "_pages_v_blocks_service_grid_items" CASCADE;
  DROP TABLE "_pages_v_blocks_service_grid" CASCADE;
  DROP TABLE "_pages_v_blocks_our_process_block_cards" CASCADE;
  DROP TABLE "_pages_v_blocks_our_process_block" CASCADE;
  DROP TABLE "_pages_v_blocks_usp_table_columns" CASCADE;
  DROP TABLE "_pages_v_blocks_usp_table_rows" CASCADE;
  DROP TABLE "_pages_v_blocks_usp_table" CASCADE;
  DROP TABLE "_pages_v_blocks_numbers_section_cards" CASCADE;
  DROP TABLE "_pages_v_blocks_numbers_section" CASCADE;
  DROP TABLE "_pages_v_blocks_testimonials_block_items" CASCADE;
  DROP TABLE "_pages_v_blocks_testimonials_block" CASCADE;
  DROP TABLE "_pages_v_blocks_contact_us_section_list_items" CASCADE;
  DROP TABLE "_pages_v_blocks_contact_us_section" CASCADE;
  DROP TABLE "_pages_v_blocks_level_up_c_t_a" CASCADE;
  DROP TABLE "_pages_v_blocks_case_studies_block_items" CASCADE;
  DROP TABLE "_pages_v_blocks_case_studies_block" CASCADE;
  DROP TABLE "_pages_v_blocks_our_approach_items" CASCADE;
  DROP TABLE "_pages_v_blocks_our_approach" CASCADE;
  DROP TABLE "_pages_v_blocks_brands_block_items" CASCADE;
  DROP TABLE "_pages_v_blocks_brands_block" CASCADE;
  DROP TABLE "_pages_v_blocks_service_details_banner_items" CASCADE;
  DROP TABLE "_pages_v_blocks_service_details_banner" CASCADE;
  DROP TABLE "_pages_v_blocks_business_block" CASCADE;
  DROP TABLE "_pages_v_blocks_page_banner" CASCADE;
  DROP TABLE "_pages_v_blocks_title_with_tabs_tabs" CASCADE;
  DROP TABLE "_pages_v_blocks_title_with_tabs" CASCADE;
  DROP TABLE "_pages_v_blocks_book_consultation" CASCADE;
  DROP TABLE "_pages_v_blocks_about_us_strategy_numbers" CASCADE;
  DROP TABLE "_pages_v_blocks_about_us_strategy" CASCADE;
  DROP TABLE "_pages_v_blocks_our_story_year_items" CASCADE;
  DROP TABLE "_pages_v_blocks_our_story" CASCADE;
  DROP TABLE "_pages_v_blocks_awards_recognition_items" CASCADE;
  DROP TABLE "_pages_v_blocks_awards_recognition" CASCADE;
  DROP TABLE "_pages_v_blocks_our_clients_clients" CASCADE;
  DROP TABLE "_pages_v_blocks_our_clients" CASCADE;
  DROP TABLE "_pages_v_blocks_join_our_team" CASCADE;
  DROP TABLE "_pages_v_blocks_case_studies_banner" CASCADE;
  DROP TABLE "_pages_v_blocks_all_case_studies" CASCADE;
  DROP TABLE "_pages_v_blocks_work_together" CASCADE;
  DROP TABLE "_pages_v_blocks_case_summary" CASCADE;
  DROP TABLE "_pages_v_blocks_case_details_gallery" CASCADE;
  DROP TABLE "_pages_v_blocks_case_details_project" CASCADE;
  DROP TABLE "_pages_v_blocks_case_details_gallery_two" CASCADE;
  DROP TABLE "_pages_v_blocks_case_details" CASCADE;
  DROP TABLE "_pages_v_blocks_included_services_services" CASCADE;
  DROP TABLE "_pages_v_blocks_included_services" CASCADE;
  DROP TABLE "_pages_v_blocks_industry_experience_items" CASCADE;
  DROP TABLE "_pages_v_blocks_industry_experience" CASCADE;
  DROP TABLE "_pages_v_blocks_our_process_items" CASCADE;
  DROP TABLE "_pages_v_blocks_our_process" CASCADE;
  DROP TABLE "_pages_v_blocks_life_at_n_h_items" CASCADE;
  DROP TABLE "_pages_v_blocks_life_at_n_h" CASCADE;
  DROP TABLE "_pages_v_blocks_featured_blog_post" CASCADE;
  DROP TABLE "_pages_v_blocks_blog_posts" CASCADE;
  DROP TABLE "_pages_v_blocks_project_discussion" CASCADE;
  DROP TABLE "_pages_v_blocks_office_address_addresses" CASCADE;
  DROP TABLE "_pages_v_blocks_office_address" CASCADE;
  DROP TABLE "_pages_v_blocks_awards_block_items" CASCADE;
  DROP TABLE "_pages_v_blocks_awards_block" CASCADE;
  DROP TABLE "_pages_v_blocks_video_testimonial_videos" CASCADE;
  DROP TABLE "_pages_v_blocks_video_testimonial" CASCADE;
  DROP TABLE "_pages_v_blocks_rich_content" CASCADE;
  DROP TABLE "_pages_v_rels" CASCADE;
  DROP TABLE "services_blocks_home_hero_highlights" CASCADE;
  DROP TABLE "services_blocks_home_hero_client_logos" CASCADE;
  DROP TABLE "services_blocks_home_hero" CASCADE;
  DROP TABLE "services_blocks_why_notionhive_cards" CASCADE;
  DROP TABLE "services_blocks_why_notionhive" CASCADE;
  DROP TABLE "services_blocks_service_grid_items" CASCADE;
  DROP TABLE "services_blocks_service_grid" CASCADE;
  DROP TABLE "services_blocks_our_process_block_cards" CASCADE;
  DROP TABLE "services_blocks_our_process_block" CASCADE;
  DROP TABLE "services_blocks_usp_table_columns" CASCADE;
  DROP TABLE "services_blocks_usp_table_rows" CASCADE;
  DROP TABLE "services_blocks_usp_table" CASCADE;
  DROP TABLE "services_blocks_numbers_section_cards" CASCADE;
  DROP TABLE "services_blocks_numbers_section" CASCADE;
  DROP TABLE "services_blocks_testimonials_block_items" CASCADE;
  DROP TABLE "services_blocks_testimonials_block" CASCADE;
  DROP TABLE "services_blocks_contact_us_section_list_items" CASCADE;
  DROP TABLE "services_blocks_contact_us_section" CASCADE;
  DROP TABLE "services_blocks_level_up_c_t_a" CASCADE;
  DROP TABLE "services_blocks_case_studies_block_items" CASCADE;
  DROP TABLE "services_blocks_case_studies_block" CASCADE;
  DROP TABLE "services_blocks_our_approach_items" CASCADE;
  DROP TABLE "services_blocks_our_approach" CASCADE;
  DROP TABLE "services_blocks_brands_block_items" CASCADE;
  DROP TABLE "services_blocks_brands_block" CASCADE;
  DROP TABLE "services_blocks_service_details_banner_items" CASCADE;
  DROP TABLE "services_blocks_service_details_banner" CASCADE;
  DROP TABLE "services_blocks_business_block" CASCADE;
  DROP TABLE "services_blocks_page_banner" CASCADE;
  DROP TABLE "services_blocks_title_with_tabs_tabs" CASCADE;
  DROP TABLE "services_blocks_title_with_tabs" CASCADE;
  DROP TABLE "services_blocks_book_consultation" CASCADE;
  DROP TABLE "services_blocks_about_us_strategy_numbers" CASCADE;
  DROP TABLE "services_blocks_about_us_strategy" CASCADE;
  DROP TABLE "services_blocks_our_story_year_items" CASCADE;
  DROP TABLE "services_blocks_our_story" CASCADE;
  DROP TABLE "services_blocks_awards_recognition_items" CASCADE;
  DROP TABLE "services_blocks_awards_recognition" CASCADE;
  DROP TABLE "services_blocks_our_clients_clients" CASCADE;
  DROP TABLE "services_blocks_our_clients" CASCADE;
  DROP TABLE "services_blocks_join_our_team" CASCADE;
  DROP TABLE "services_blocks_case_studies_banner" CASCADE;
  DROP TABLE "services_blocks_all_case_studies" CASCADE;
  DROP TABLE "services_blocks_work_together" CASCADE;
  DROP TABLE "services_blocks_case_summary" CASCADE;
  DROP TABLE "services_blocks_case_details_gallery" CASCADE;
  DROP TABLE "services_blocks_case_details_project" CASCADE;
  DROP TABLE "services_blocks_case_details_gallery_two" CASCADE;
  DROP TABLE "services_blocks_case_details" CASCADE;
  DROP TABLE "services_blocks_included_services_services" CASCADE;
  DROP TABLE "services_blocks_included_services" CASCADE;
  DROP TABLE "services_blocks_industry_experience_items" CASCADE;
  DROP TABLE "services_blocks_industry_experience" CASCADE;
  DROP TABLE "services_blocks_our_process_items" CASCADE;
  DROP TABLE "services_blocks_our_process" CASCADE;
  DROP TABLE "services_blocks_life_at_n_h_items" CASCADE;
  DROP TABLE "services_blocks_life_at_n_h" CASCADE;
  DROP TABLE "services_blocks_featured_blog_post" CASCADE;
  DROP TABLE "services_blocks_blog_posts" CASCADE;
  DROP TABLE "services_blocks_project_discussion" CASCADE;
  DROP TABLE "services_blocks_office_address_addresses" CASCADE;
  DROP TABLE "services_blocks_office_address" CASCADE;
  DROP TABLE "services_blocks_awards_block_items" CASCADE;
  DROP TABLE "services_blocks_awards_block" CASCADE;
  DROP TABLE "services_blocks_video_testimonial_videos" CASCADE;
  DROP TABLE "services_blocks_video_testimonial" CASCADE;
  DROP TABLE "services_blocks_rich_content" CASCADE;
  DROP TABLE "_services_v_blocks_home_hero_highlights" CASCADE;
  DROP TABLE "_services_v_blocks_home_hero_client_logos" CASCADE;
  DROP TABLE "_services_v_blocks_home_hero" CASCADE;
  DROP TABLE "_services_v_blocks_why_notionhive_cards" CASCADE;
  DROP TABLE "_services_v_blocks_why_notionhive" CASCADE;
  DROP TABLE "_services_v_blocks_service_grid_items" CASCADE;
  DROP TABLE "_services_v_blocks_service_grid" CASCADE;
  DROP TABLE "_services_v_blocks_our_process_block_cards" CASCADE;
  DROP TABLE "_services_v_blocks_our_process_block" CASCADE;
  DROP TABLE "_services_v_blocks_usp_table_columns" CASCADE;
  DROP TABLE "_services_v_blocks_usp_table_rows" CASCADE;
  DROP TABLE "_services_v_blocks_usp_table" CASCADE;
  DROP TABLE "_services_v_blocks_numbers_section_cards" CASCADE;
  DROP TABLE "_services_v_blocks_numbers_section" CASCADE;
  DROP TABLE "_services_v_blocks_testimonials_block_items" CASCADE;
  DROP TABLE "_services_v_blocks_testimonials_block" CASCADE;
  DROP TABLE "_services_v_blocks_contact_us_section_list_items" CASCADE;
  DROP TABLE "_services_v_blocks_contact_us_section" CASCADE;
  DROP TABLE "_services_v_blocks_level_up_c_t_a" CASCADE;
  DROP TABLE "_services_v_blocks_case_studies_block_items" CASCADE;
  DROP TABLE "_services_v_blocks_case_studies_block" CASCADE;
  DROP TABLE "_services_v_blocks_our_approach_items" CASCADE;
  DROP TABLE "_services_v_blocks_our_approach" CASCADE;
  DROP TABLE "_services_v_blocks_brands_block_items" CASCADE;
  DROP TABLE "_services_v_blocks_brands_block" CASCADE;
  DROP TABLE "_services_v_blocks_service_details_banner_items" CASCADE;
  DROP TABLE "_services_v_blocks_service_details_banner" CASCADE;
  DROP TABLE "_services_v_blocks_business_block" CASCADE;
  DROP TABLE "_services_v_blocks_page_banner" CASCADE;
  DROP TABLE "_services_v_blocks_title_with_tabs_tabs" CASCADE;
  DROP TABLE "_services_v_blocks_title_with_tabs" CASCADE;
  DROP TABLE "_services_v_blocks_book_consultation" CASCADE;
  DROP TABLE "_services_v_blocks_about_us_strategy_numbers" CASCADE;
  DROP TABLE "_services_v_blocks_about_us_strategy" CASCADE;
  DROP TABLE "_services_v_blocks_our_story_year_items" CASCADE;
  DROP TABLE "_services_v_blocks_our_story" CASCADE;
  DROP TABLE "_services_v_blocks_awards_recognition_items" CASCADE;
  DROP TABLE "_services_v_blocks_awards_recognition" CASCADE;
  DROP TABLE "_services_v_blocks_our_clients_clients" CASCADE;
  DROP TABLE "_services_v_blocks_our_clients" CASCADE;
  DROP TABLE "_services_v_blocks_join_our_team" CASCADE;
  DROP TABLE "_services_v_blocks_case_studies_banner" CASCADE;
  DROP TABLE "_services_v_blocks_all_case_studies" CASCADE;
  DROP TABLE "_services_v_blocks_work_together" CASCADE;
  DROP TABLE "_services_v_blocks_case_summary" CASCADE;
  DROP TABLE "_services_v_blocks_case_details_gallery" CASCADE;
  DROP TABLE "_services_v_blocks_case_details_project" CASCADE;
  DROP TABLE "_services_v_blocks_case_details_gallery_two" CASCADE;
  DROP TABLE "_services_v_blocks_case_details" CASCADE;
  DROP TABLE "_services_v_blocks_included_services_services" CASCADE;
  DROP TABLE "_services_v_blocks_included_services" CASCADE;
  DROP TABLE "_services_v_blocks_industry_experience_items" CASCADE;
  DROP TABLE "_services_v_blocks_industry_experience" CASCADE;
  DROP TABLE "_services_v_blocks_our_process_items" CASCADE;
  DROP TABLE "_services_v_blocks_our_process" CASCADE;
  DROP TABLE "_services_v_blocks_life_at_n_h_items" CASCADE;
  DROP TABLE "_services_v_blocks_life_at_n_h" CASCADE;
  DROP TABLE "_services_v_blocks_featured_blog_post" CASCADE;
  DROP TABLE "_services_v_blocks_blog_posts" CASCADE;
  DROP TABLE "_services_v_blocks_project_discussion" CASCADE;
  DROP TABLE "_services_v_blocks_office_address_addresses" CASCADE;
  DROP TABLE "_services_v_blocks_office_address" CASCADE;
  DROP TABLE "_services_v_blocks_awards_block_items" CASCADE;
  DROP TABLE "_services_v_blocks_awards_block" CASCADE;
  DROP TABLE "_services_v_blocks_video_testimonial_videos" CASCADE;
  DROP TABLE "_services_v_blocks_video_testimonial" CASCADE;
  DROP TABLE "_services_v_blocks_rich_content" CASCADE;
  DROP TABLE "our_work_blocks_home_hero_highlights" CASCADE;
  DROP TABLE "our_work_blocks_home_hero_client_logos" CASCADE;
  DROP TABLE "our_work_blocks_home_hero" CASCADE;
  DROP TABLE "our_work_blocks_why_notionhive_cards" CASCADE;
  DROP TABLE "our_work_blocks_why_notionhive" CASCADE;
  DROP TABLE "our_work_blocks_service_grid_items" CASCADE;
  DROP TABLE "our_work_blocks_service_grid" CASCADE;
  DROP TABLE "our_work_blocks_our_process_block_cards" CASCADE;
  DROP TABLE "our_work_blocks_our_process_block" CASCADE;
  DROP TABLE "our_work_blocks_usp_table_columns" CASCADE;
  DROP TABLE "our_work_blocks_usp_table_rows" CASCADE;
  DROP TABLE "our_work_blocks_usp_table" CASCADE;
  DROP TABLE "our_work_blocks_numbers_section_cards" CASCADE;
  DROP TABLE "our_work_blocks_numbers_section" CASCADE;
  DROP TABLE "our_work_blocks_testimonials_block_items" CASCADE;
  DROP TABLE "our_work_blocks_testimonials_block" CASCADE;
  DROP TABLE "our_work_blocks_contact_us_section_list_items" CASCADE;
  DROP TABLE "our_work_blocks_contact_us_section" CASCADE;
  DROP TABLE "our_work_blocks_level_up_c_t_a" CASCADE;
  DROP TABLE "our_work_blocks_case_studies_block_items" CASCADE;
  DROP TABLE "our_work_blocks_case_studies_block" CASCADE;
  DROP TABLE "our_work_blocks_our_approach_items" CASCADE;
  DROP TABLE "our_work_blocks_our_approach" CASCADE;
  DROP TABLE "our_work_blocks_brands_block_items" CASCADE;
  DROP TABLE "our_work_blocks_brands_block" CASCADE;
  DROP TABLE "our_work_blocks_service_details_banner_items" CASCADE;
  DROP TABLE "our_work_blocks_service_details_banner" CASCADE;
  DROP TABLE "our_work_blocks_business_block" CASCADE;
  DROP TABLE "our_work_blocks_page_banner" CASCADE;
  DROP TABLE "our_work_blocks_title_with_tabs_tabs" CASCADE;
  DROP TABLE "our_work_blocks_title_with_tabs" CASCADE;
  DROP TABLE "our_work_blocks_book_consultation" CASCADE;
  DROP TABLE "our_work_blocks_about_us_strategy_numbers" CASCADE;
  DROP TABLE "our_work_blocks_about_us_strategy" CASCADE;
  DROP TABLE "our_work_blocks_our_story_year_items" CASCADE;
  DROP TABLE "our_work_blocks_our_story" CASCADE;
  DROP TABLE "our_work_blocks_awards_recognition_items" CASCADE;
  DROP TABLE "our_work_blocks_awards_recognition" CASCADE;
  DROP TABLE "our_work_blocks_our_clients_clients" CASCADE;
  DROP TABLE "our_work_blocks_our_clients" CASCADE;
  DROP TABLE "our_work_blocks_join_our_team" CASCADE;
  DROP TABLE "our_work_blocks_case_studies_banner" CASCADE;
  DROP TABLE "our_work_blocks_all_case_studies" CASCADE;
  DROP TABLE "our_work_blocks_work_together" CASCADE;
  DROP TABLE "our_work_blocks_case_summary" CASCADE;
  DROP TABLE "our_work_blocks_case_details_gallery" CASCADE;
  DROP TABLE "our_work_blocks_case_details_project" CASCADE;
  DROP TABLE "our_work_blocks_case_details_gallery_two" CASCADE;
  DROP TABLE "our_work_blocks_case_details" CASCADE;
  DROP TABLE "our_work_blocks_included_services_services" CASCADE;
  DROP TABLE "our_work_blocks_included_services" CASCADE;
  DROP TABLE "our_work_blocks_industry_experience_items" CASCADE;
  DROP TABLE "our_work_blocks_industry_experience" CASCADE;
  DROP TABLE "our_work_blocks_our_process_items" CASCADE;
  DROP TABLE "our_work_blocks_our_process" CASCADE;
  DROP TABLE "our_work_blocks_life_at_n_h_items" CASCADE;
  DROP TABLE "our_work_blocks_life_at_n_h" CASCADE;
  DROP TABLE "our_work_blocks_featured_blog_post" CASCADE;
  DROP TABLE "our_work_blocks_blog_posts" CASCADE;
  DROP TABLE "our_work_blocks_project_discussion" CASCADE;
  DROP TABLE "our_work_blocks_office_address_addresses" CASCADE;
  DROP TABLE "our_work_blocks_office_address" CASCADE;
  DROP TABLE "our_work_blocks_awards_block_items" CASCADE;
  DROP TABLE "our_work_blocks_awards_block" CASCADE;
  DROP TABLE "our_work_blocks_video_testimonial_videos" CASCADE;
  DROP TABLE "our_work_blocks_video_testimonial" CASCADE;
  DROP TABLE "our_work_blocks_rich_content" CASCADE;
  DROP TABLE "_our_work_v_blocks_home_hero_highlights" CASCADE;
  DROP TABLE "_our_work_v_blocks_home_hero_client_logos" CASCADE;
  DROP TABLE "_our_work_v_blocks_home_hero" CASCADE;
  DROP TABLE "_our_work_v_blocks_why_notionhive_cards" CASCADE;
  DROP TABLE "_our_work_v_blocks_why_notionhive" CASCADE;
  DROP TABLE "_our_work_v_blocks_service_grid_items" CASCADE;
  DROP TABLE "_our_work_v_blocks_service_grid" CASCADE;
  DROP TABLE "_our_work_v_blocks_our_process_block_cards" CASCADE;
  DROP TABLE "_our_work_v_blocks_our_process_block" CASCADE;
  DROP TABLE "_our_work_v_blocks_usp_table_columns" CASCADE;
  DROP TABLE "_our_work_v_blocks_usp_table_rows" CASCADE;
  DROP TABLE "_our_work_v_blocks_usp_table" CASCADE;
  DROP TABLE "_our_work_v_blocks_numbers_section_cards" CASCADE;
  DROP TABLE "_our_work_v_blocks_numbers_section" CASCADE;
  DROP TABLE "_our_work_v_blocks_testimonials_block_items" CASCADE;
  DROP TABLE "_our_work_v_blocks_testimonials_block" CASCADE;
  DROP TABLE "_our_work_v_blocks_contact_us_section_list_items" CASCADE;
  DROP TABLE "_our_work_v_blocks_contact_us_section" CASCADE;
  DROP TABLE "_our_work_v_blocks_level_up_c_t_a" CASCADE;
  DROP TABLE "_our_work_v_blocks_case_studies_block_items" CASCADE;
  DROP TABLE "_our_work_v_blocks_case_studies_block" CASCADE;
  DROP TABLE "_our_work_v_blocks_our_approach_items" CASCADE;
  DROP TABLE "_our_work_v_blocks_our_approach" CASCADE;
  DROP TABLE "_our_work_v_blocks_brands_block_items" CASCADE;
  DROP TABLE "_our_work_v_blocks_brands_block" CASCADE;
  DROP TABLE "_our_work_v_blocks_service_details_banner_items" CASCADE;
  DROP TABLE "_our_work_v_blocks_service_details_banner" CASCADE;
  DROP TABLE "_our_work_v_blocks_business_block" CASCADE;
  DROP TABLE "_our_work_v_blocks_page_banner" CASCADE;
  DROP TABLE "_our_work_v_blocks_title_with_tabs_tabs" CASCADE;
  DROP TABLE "_our_work_v_blocks_title_with_tabs" CASCADE;
  DROP TABLE "_our_work_v_blocks_book_consultation" CASCADE;
  DROP TABLE "_our_work_v_blocks_about_us_strategy_numbers" CASCADE;
  DROP TABLE "_our_work_v_blocks_about_us_strategy" CASCADE;
  DROP TABLE "_our_work_v_blocks_our_story_year_items" CASCADE;
  DROP TABLE "_our_work_v_blocks_our_story" CASCADE;
  DROP TABLE "_our_work_v_blocks_awards_recognition_items" CASCADE;
  DROP TABLE "_our_work_v_blocks_awards_recognition" CASCADE;
  DROP TABLE "_our_work_v_blocks_our_clients_clients" CASCADE;
  DROP TABLE "_our_work_v_blocks_our_clients" CASCADE;
  DROP TABLE "_our_work_v_blocks_join_our_team" CASCADE;
  DROP TABLE "_our_work_v_blocks_case_studies_banner" CASCADE;
  DROP TABLE "_our_work_v_blocks_all_case_studies" CASCADE;
  DROP TABLE "_our_work_v_blocks_work_together" CASCADE;
  DROP TABLE "_our_work_v_blocks_case_summary" CASCADE;
  DROP TABLE "_our_work_v_blocks_case_details_gallery" CASCADE;
  DROP TABLE "_our_work_v_blocks_case_details_project" CASCADE;
  DROP TABLE "_our_work_v_blocks_case_details_gallery_two" CASCADE;
  DROP TABLE "_our_work_v_blocks_case_details" CASCADE;
  DROP TABLE "_our_work_v_blocks_included_services_services" CASCADE;
  DROP TABLE "_our_work_v_blocks_included_services" CASCADE;
  DROP TABLE "_our_work_v_blocks_industry_experience_items" CASCADE;
  DROP TABLE "_our_work_v_blocks_industry_experience" CASCADE;
  DROP TABLE "_our_work_v_blocks_our_process_items" CASCADE;
  DROP TABLE "_our_work_v_blocks_our_process" CASCADE;
  DROP TABLE "_our_work_v_blocks_life_at_n_h_items" CASCADE;
  DROP TABLE "_our_work_v_blocks_life_at_n_h" CASCADE;
  DROP TABLE "_our_work_v_blocks_featured_blog_post" CASCADE;
  DROP TABLE "_our_work_v_blocks_blog_posts" CASCADE;
  DROP TABLE "_our_work_v_blocks_project_discussion" CASCADE;
  DROP TABLE "_our_work_v_blocks_office_address_addresses" CASCADE;
  DROP TABLE "_our_work_v_blocks_office_address" CASCADE;
  DROP TABLE "_our_work_v_blocks_awards_block_items" CASCADE;
  DROP TABLE "_our_work_v_blocks_awards_block" CASCADE;
  DROP TABLE "_our_work_v_blocks_video_testimonial_videos" CASCADE;
  DROP TABLE "_our_work_v_blocks_video_testimonial" CASCADE;
  DROP TABLE "_our_work_v_blocks_rich_content" CASCADE;
  DROP TABLE "forms_blocks_checkbox" CASCADE;
  DROP TABLE "forms_blocks_country" CASCADE;
  DROP TABLE "forms_blocks_email" CASCADE;
  DROP TABLE "forms_blocks_message" CASCADE;
  DROP TABLE "forms_blocks_number" CASCADE;
  DROP TABLE "forms_blocks_select_options" CASCADE;
  DROP TABLE "forms_blocks_select" CASCADE;
  DROP TABLE "forms_blocks_state" CASCADE;
  DROP TABLE "forms_blocks_text" CASCADE;
  DROP TABLE "forms_blocks_textarea" CASCADE;
  ALTER TABLE "services_rels" DROP CONSTRAINT "services_rels_blogs_fk";
  
  ALTER TABLE "_services_v_rels" DROP CONSTRAINT "_services_v_rels_blogs_fk";
  
  ALTER TABLE "our_work_rels" DROP CONSTRAINT "our_work_rels_blogs_fk";
  
  ALTER TABLE "_our_work_v_rels" DROP CONSTRAINT "_our_work_v_rels_blogs_fk";
  
  DROP INDEX "services_rels_blogs_id_idx";
  DROP INDEX "_services_v_rels_blogs_id_idx";
  DROP INDEX "our_work_rels_blogs_id_idx";
  DROP INDEX "_our_work_v_rels_blogs_id_idx";
  ALTER TABLE "pages" ADD COLUMN "layout" jsonb;
  ALTER TABLE "_pages_v" ADD COLUMN "version_layout" jsonb;
  ALTER TABLE "services" ADD COLUMN "layout" jsonb;
  ALTER TABLE "_services_v" ADD COLUMN "version_layout" jsonb;
  ALTER TABLE "our_work" ADD COLUMN "layout" jsonb;
  ALTER TABLE "_our_work_v" ADD COLUMN "version_layout" jsonb;
  ALTER TABLE "forms" ADD COLUMN "fields" jsonb;
  ALTER TABLE "services_rels" DROP COLUMN "blogs_id";
  ALTER TABLE "_services_v_rels" DROP COLUMN "blogs_id";
  ALTER TABLE "our_work_rels" DROP COLUMN "blogs_id";
  ALTER TABLE "_our_work_v_rels" DROP COLUMN "blogs_id";
  DROP TYPE "public"."enum_pages_blocks_home_hero_button_target";
  DROP TYPE "public"."enum_items_button_target";
  DROP TYPE "public"."enum_pages_blocks_service_grid_variant";
  DROP TYPE "public"."enum_pages_blocks_service_grid_button_target";
  DROP TYPE "public"."enum_pages_blocks_testimonials_block_variant";
  DROP TYPE "public"."enum_pages_blocks_testimonials_block_button_target";
  DROP TYPE "public"."enum_pages_blocks_level_up_c_t_a_button_target";
  DROP TYPE "public"."enum_pages_blocks_case_studies_block_variant";
  DROP TYPE "public"."enum_pages_blocks_brands_block_variant";
  DROP TYPE "public"."enum_pages_blocks_brands_block_button_target";
  DROP TYPE "public"."enum_pages_blocks_join_our_team_button_target";
  DROP TYPE "public"."enum_pages_blocks_case_summary_button_target";
  DROP TYPE "public"."enum_pages_blocks_life_at_n_h_items_button_target";
  DROP TYPE "public"."enum__pages_v_blocks_home_hero_button_target";
  DROP TYPE "public"."enum__items_v_button_target";
  DROP TYPE "public"."enum__pages_v_blocks_service_grid_variant";
  DROP TYPE "public"."enum__pages_v_blocks_service_grid_button_target";
  DROP TYPE "public"."enum__pages_v_blocks_testimonials_block_variant";
  DROP TYPE "public"."enum__pages_v_blocks_testimonials_block_button_target";
  DROP TYPE "public"."enum__pages_v_blocks_level_up_c_t_a_button_target";
  DROP TYPE "public"."enum__pages_v_blocks_case_studies_block_variant";
  DROP TYPE "public"."enum__pages_v_blocks_brands_block_variant";
  DROP TYPE "public"."enum__pages_v_blocks_brands_block_button_target";
  DROP TYPE "public"."enum__pages_v_blocks_join_our_team_button_target";
  DROP TYPE "public"."enum__pages_v_blocks_case_summary_button_target";
  DROP TYPE "public"."enum__pages_v_blocks_life_at_n_h_items_button_target";
  DROP TYPE "public"."enum_services_blocks_home_hero_button_target";
  DROP TYPE "public"."enum_services_blocks_service_grid_variant";
  DROP TYPE "public"."enum_services_blocks_service_grid_button_target";
  DROP TYPE "public"."enum_services_blocks_testimonials_block_variant";
  DROP TYPE "public"."enum_services_blocks_testimonials_block_button_target";
  DROP TYPE "public"."enum_services_blocks_level_up_c_t_a_button_target";
  DROP TYPE "public"."enum_services_blocks_case_studies_block_variant";
  DROP TYPE "public"."enum_services_blocks_brands_block_variant";
  DROP TYPE "public"."enum_services_blocks_brands_block_button_target";
  DROP TYPE "public"."enum_services_blocks_join_our_team_button_target";
  DROP TYPE "public"."enum_services_blocks_case_summary_button_target";
  DROP TYPE "public"."enum_services_blocks_life_at_n_h_items_button_target";
  DROP TYPE "public"."enum__services_v_blocks_home_hero_button_target";
  DROP TYPE "public"."enum__services_v_blocks_service_grid_variant";
  DROP TYPE "public"."enum__services_v_blocks_service_grid_button_target";
  DROP TYPE "public"."enum__services_v_blocks_testimonials_block_variant";
  DROP TYPE "public"."enum__services_v_blocks_testimonials_block_button_target";
  DROP TYPE "public"."enum__services_v_blocks_level_up_c_t_a_button_target";
  DROP TYPE "public"."enum__services_v_blocks_case_studies_block_variant";
  DROP TYPE "public"."enum__services_v_blocks_brands_block_variant";
  DROP TYPE "public"."enum__services_v_blocks_brands_block_button_target";
  DROP TYPE "public"."enum__services_v_blocks_join_our_team_button_target";
  DROP TYPE "public"."enum__services_v_blocks_case_summary_button_target";
  DROP TYPE "public"."enum__services_v_blocks_life_at_n_h_items_button_target";
  DROP TYPE "public"."enum_our_work_blocks_home_hero_button_target";
  DROP TYPE "public"."enum_our_work_blocks_service_grid_variant";
  DROP TYPE "public"."enum_our_work_blocks_service_grid_button_target";
  DROP TYPE "public"."enum_our_work_blocks_testimonials_block_variant";
  DROP TYPE "public"."enum_our_work_blocks_testimonials_block_button_target";
  DROP TYPE "public"."enum_our_work_blocks_level_up_c_t_a_button_target";
  DROP TYPE "public"."enum_our_work_blocks_case_studies_block_variant";
  DROP TYPE "public"."enum_our_work_blocks_brands_block_variant";
  DROP TYPE "public"."enum_our_work_blocks_brands_block_button_target";
  DROP TYPE "public"."enum_our_work_blocks_join_our_team_button_target";
  DROP TYPE "public"."enum_our_work_blocks_case_summary_button_target";
  DROP TYPE "public"."enum_our_work_blocks_life_at_n_h_items_button_target";
  DROP TYPE "public"."enum__our_work_v_blocks_home_hero_button_target";
  DROP TYPE "public"."enum__our_work_v_blocks_service_grid_variant";
  DROP TYPE "public"."enum__our_work_v_blocks_service_grid_button_target";
  DROP TYPE "public"."enum__our_work_v_blocks_testimonials_block_variant";
  DROP TYPE "public"."enum__our_work_v_blocks_testimonials_block_button_target";
  DROP TYPE "public"."enum__our_work_v_blocks_level_up_c_t_a_button_target";
  DROP TYPE "public"."enum__our_work_v_blocks_case_studies_block_variant";
  DROP TYPE "public"."enum__our_work_v_blocks_brands_block_variant";
  DROP TYPE "public"."enum__our_work_v_blocks_brands_block_button_target";
  DROP TYPE "public"."enum__our_work_v_blocks_join_our_team_button_target";
  DROP TYPE "public"."enum__our_work_v_blocks_case_summary_button_target";
  DROP TYPE "public"."enum__our_work_v_blocks_life_at_n_h_items_button_target";`)
  payload.logger.info("Executed blocks to JSON migration statements.")
  
  await migrator.migrateEntitiesFromTempFolder(req, { clearBatches: true })
    
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
    // Migration code
}
